### PR TITLE
Discord Rich Presence Support

### PR DESCRIPTION
**Pull request by Windows10CE**

### CODE REVIEW

**Comment by Arkhist** [comment]
Can you explain how dependencies work with that request ?

**Comment by Windows10CE** [comment]
The DiscordRpc DLL needs to be next to the HackOnNet DLL

**Comment by Arkhist** [comment]
And does it crash if it's not there ?

**Comment by Windows10CE** [comment]
Everything works, and it will go on without the DLL if you don't have it.

**Pull request merged**
